#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Alacritty-float state=floating rectangle=1280x720+640+360
bspc rule -a Pcmanfm state=floating rectangle=1200x800+680+100
bspc rule -a ranger state=floating rectangle=1200x800+680+200
bspc rule -a Electron  state=floating rectangle=1200x800+680+100
bspc rule -a Wine  state=floating
bspc rule -a QQ state=floating
bspc rule -a Galculator state=floating
bspc rule -a jetbrains-idea state=floating rectangle=2400x1350+80+45
bspc rule -a qqmusic state=floating rectangle=1200x800+1300+100

