#!/bin/sh

source ~/.config/eww/scripts/util.sh

activespace() {
  active=($(bspc query -D -d .active --names | tr '\n' ' '))
  # echo "[$(transform ${active[*]} | tr ' ' ',')]" | jq -Mc 'unique | sort'
  echo "$(transform $active),end" | stdbuf -o0 awk -F '>>|,' '{print $1}'
}
activespace
# bspc subscribe desktop_focus node_add node_remove | while read line; do
	# activespace
	# echo "[1]"
# done
