#!/bin/sh

source ~/.config/eww/scripts/util.sh

workspaces() {
  occupied=($(bspc query -D -d .occupied --names | tr '\n' ' '))
  active=($(bspc query -D -d .active --names | tr '\n' ' '))
  workspacearry=$(echo "[$(transform ${occupied[*]} ${active[*]} | tr ' ' ',')]" | jq -Mc 'unique | sort')
  obj="{\"spaces\":\"${workspacearry}\",\"active\":$(transform ${active})}" 
  echo $obj | jq -Mc
}
workspaces
bspc subscribe desktop_focus node_add node_remove | while read  -r line; do
 	workspaces
done
